### ISSUE TITLE
Include the Project ID and Project Name in the list of devices, buckets...

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/node-red-contrib-thinger#59]
Include the Project ID and Project Name in the list of devices, buckets... as suggested in the image below.
This helps identify which device to select when they have the same name but are from different Projects.
Ex:
Device ID: xtj78
Due Name: Temperature Sensor
Project ID: **123859**
Project Name: **Company AAAAAA**

Device ID: poir96
Due Name: Temperature Sensor
Project ID: **875632**
Project Name: **Company BBBBBB**

![image](https://github.com/thinger-io/node-red-contrib-thinger/assets/22058152/36c48781-439a-4f49-b9b9-4677bd82ec11)

**Comment by bautisflow** [comment]
Hi @georgevbsantiago 

We've decided to not include this in order to avoid clutter in the options. However we've come up with an alternative, which is to include an optional filter for the project in the Server node configuration.

![thinger_server_node_config](https://github.com/user-attachments/assets/02c14cc8-b628-4a47-8131-8a24b4ded5d4)

This would query and show only the list of devices, buckets, etc. that belongs to the project, for the UI as well as for the resulting execution of all thinger nodes operations. The only downside I can think of is that a new server configuration would need to be created per project to allow the filtering. It would also allow having the current config node without project filtering.

What do you think of this solution?

**Comment by bautisflow** [comment]
We are currently looking into a different approach, in which the project will be automatically set by an environment variable set for the flow or a group of nodes, so no additional server config nodes would be required
